<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">



</head>

<body style="overflow-x: hidden" class="loading">



<main> <div id="wrapper">


        <div id="preload">
            <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Bild1.jpg'); ?>'>
            <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Bild2.jpg'); ?>'>
            <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Bild3.jpg'); ?>'>
            <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Bild4.jpg'); ?>'>
            <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Bild5.jpg'); ?>'>
            <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Bild6.1.jpg'); ?>'>
            <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Bild6.2.jpg'); ?>'>
            <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Bild6.3.jpg'); ?>'>
            <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Bild7.jpg'); ?>'>
            <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Bild8.jpg'); ?>'>


        </div>


        <div id="skrollr-body">
</div>
        <section id="slide-1" class="homeSlide">
            <div class="bcg"
                 data-center="background-position: 50% 0px;"
                 data-top-bottom="background-position: 50% -100px;"
                 data-anchor-target="#slide-1"
            >

                <div class="hsContainer">
                    <a href="#slide-2" style="
            left: 0 !important;
            margin-left: 15% !important;
            margin-top: 20%;
            position: absolute;
            /* background-color: black; */
            left: 50%;
            height: 46px;
            margin-left: -23px;
            border-radius: 100%;
            box-sizing: border-box;"><span style="background-color: white !important;"></span>Scrollen</a>
                    <div class="hsContent"
                         data-center="bottom: 200px; opacity: 1"
                         data-top="bottom: 1200px; opacity: 0"
                         data-anchor-target="#slide-1 h2">
                        <h2 >Das <span style="color : red">KENIA-PROJEKT  </span> ist seit über <span class="counter" style=" color: red">20 </span> Jahren in der Hilfe zur Selbsthilfe in Ostafrika tätig.Von Deutschland aus wird unterstützt und koordiniert. Die eigentliche Arbeit läuft aber vor Ort in Kenia und Uganda und neuerdings in Äthiopien. So wächst ein Netzwerk: Freunde Blaues Kreuz Ostafrika. <div id="slide8h2"></div></h2>

                    </div>
                </div>
            </div>
        </section>

        <section id="slide-2" class="homeSlide">
            <div class="bcg"
                 data-center="background-position: 50% 10px;"
                 data-top-bottom="background-position: 50% -100px;"
                 data-bottom-top="background-position: 50% 100px;"
                 data-anchor-target="#slide-2"
            >
                <div class="hsContainer">
                    <a href="#slide-3" style="
            left: 0 !important;
            margin-left: 15% !important;
            margin-top: 20%;
            position: absolute;
            /* background-color: black; */
            left: 50%;
            height: 46px;
            margin-left: -23px;
            border-radius: 100%;
            box-sizing: border-box;"><span style="background-color: white !important;"></span>Scrollen</a>
                    <div class="hsContent"
                         data-center="opacity: 1"
                         data-center-top="opacity: 0"
                         data--100-bottom="opacity: 0;"
                         data-anchor-target="#slide-2 h2"
                    >

                        <h2> <span style="color : red">Wie entstand die Arbeit </span> <p></p> Sie begann in einem Kenia-Urlaub. Die Begegnung mit akuter Not berührte und aktivierte. Daraus entstand eine Hilfs – Initiative. Ihr schlossen sich immer mehr an: Mitarbeiter des Kran-kenhauses, Diakonissen, Patienten, weitere Freunde.  </h2>
                    </div>
                </div>
            </div>
        </section>

        <section id="slide-3" class="homeSlide">
            <div class="bcg"
                 data-center="background-position: 50% 0px;"
                 data-top-bottom="background-position: 50% -100px;"
                 data-bottom-top="background-position: 50% 100px;"
                 data-anchor-target="#slide-3"
            >
                <div class="hsContainer">
                    <a href="#slide-4" style="
        left: 0 !important;
            margin-left: 15% !important;
            margin-top: 20%;
            position: absolute;
            /* background-color: black; */
            left: 50%;
            height: 46px;
            margin-left: -23px;
            border-radius: 100%;
            box-sizing: border-box;"><span style="background-color: white !important;"></span>Scrollen</a>
                    <div class="hsContent"
                         data--50-bottom="opacity: 0;"
                         data--200-bottom="opacity: 1;"
                         data-center="opacity: 1"
                         data-200-top="opacity: 0"
                         data-anchor-target="#slide-3 h2"
                    >
                        <h2> <span style="color : red">Zielgruppen</span> <p></p>Die Arbeit hat <span class="counter" style="display: inline-block;color:red">2</span> Zielgruppen, einmal Kinder und Jugendliche in Risikosituationen, zum anderen suchtgefährdete Personen.</h2>
                    </div>
                </div>



            </div>
        </section>

        <section id="slide-4" class="homeSlide">
            <div class="bcg"
                 data-center="background-position: 50% 10px;"
                 data-top-bottom="background-position: 50% -100px;"
                 data-bottom-top="background-position: 50% 100px;"
                 data-anchor-target="#slide-4"
            >
                <div class="hsContainer">
                    <a href="#slide-5" style="
        left: 0 !important;
            margin-left: 15% !important;
            margin-top: 20%;
            position: absolute;
            /* background-color: black; */
            left: 50%;
            height: 46px;
            margin-left: -23px;
            border-radius: 100%;
            box-sizing: border-box;"><span style="background-color: white !important;"></span>Scrollen</a>
                    <div class="hsContent"
                         data-center="opacity: 1"
                         data-center-top="opacity: 0"
                         data--100-bottom="opacity: 0;"
                         data-anchor-target="#slide-4"
                    >
                        <h2> <span style="color : red">Prinzip der Arbeit </span> <p></p>Wir suchen engagierte Leute vor Ort, die schon helfen. Mit ihnen verbinden wir uns. Wirunterstützen   sie   dabei,   ihre   Arbeiten   zu   entwickeln.   Grundsätze   sind   Eigenständigkeit,solidarische Selbsthilfe und Transparenz bei der Verwendung der Mittel vor Ort. </h2>
                    </div>
                </div>
            </div>
        </section>


        <section id="slide-5" class="homeSlide">
            <div class="bcg"
                 data-center="background-position: 50% 0px;"
                 data-top-bottom="background-position: 50% -100px;"
                 data-bottom-top="background-position: 50% 100px;"
                 data-anchor-target="#slide-5"
            >
                <div class="hsContainer">
                    <a href="#slide-61" style="
        left: 0 !important;
            margin-left: 15% !important;
            margin-top: 20%;
            position: absolute;
            /* background-color: black; */
            left: 50%;
            height: 46px;
            margin-left: -23px;
            border-radius: 100%;
            box-sizing: border-box;"><span style="background-color: white !important;"></span>Scrollen</a>
                    <div class="hsContent"
                         data--50-bottom="opacity: 0;"
                         data--200-bottom="opacity: 1;"
                         data-center="opacity: 1"
                         data-200-top="opacity: 0"
                         data-anchor-target="#slide-5 h2"
                    >
                        <h2> <span style="color : red">Einsatzgebiete und Mission </span> <p></p> Es  sind  besonders  soziale  Brennpunkte,  z.B.  Slums,  auf  der  Straße,  in  Gebieten  mit  hoher Suchtgefährdung. Einige Stichworte: Mehr als <span class="counter" style="display: inline-block;color:red">100</span> einheimische ehrenamtliche Helfer, ca. <span class="counter" style="display: inline-block;color:red">35</span> Selbsthilfegruppen, viele Kinder und Jugendliche in Projekten, ca. <span class="counter" style="display: inline-block;color:red">150</span> Kinder in Sponsoringprogrammen, <span class="counter" style="display: inline-block;color:red">6</span>  Kinder – bzw.  Rehaheime  in der  Förderung. Unsere Motivation: Wir  bekommen Chancen und wir teilen Chancen. So hat uns Gott geschaffen.</h2>
                    </div>
                </div>



            </div>
        </section>


        <section id="slide-61" class="homeSlide">
            <div class="bcg"
                 data-center="background-position: 50% 0px;"
                 data-top-bottom="background-position: 50% -100px;"
                 data-bottom-top="background-position: 50% 100px;"
                 data-anchor-target="#slide-61"
            >
                <div class="hsContainer">
                    <a href="#slide-62" style="
        left: 0 !important;
            margin-left: 15% !important;
            margin-top: 20%;
            position: absolute;
            /* background-color: black; */
            left: 50%;
            height: 46px;
            margin-left: -23px;
            border-radius: 100%;
            box-sizing: border-box;"><span style="background-color: white !important;"></span>Scrollen</a>
                    <div class="hsContent"
                         data--50-bottom="opacity: 0;"
                         data--200-bottom="opacity: 1;"
                         data-center="opacity: 1"
                         data-200-top="opacity: 0"
                         data-anchor-target="#slide-61 h2"
                    >
                        <h2> <span style="color : red">Aktivitäten </span><p></p> Sie sind vielfältig: <p></p>  <span style="color : red">1.  Information: </span> <p></p> Aufklärungsveranstaltungen   auf   Märkten   und   in   Kirchen,   Seminare   für Betroffene und ehrenamtliche Helfer. </h2>
                    </div>
                </div>



            </div>
        </section>

        <section id="slide-62" class="homeSlide">
            <div class="bcg"
                 data-center="background-position: 50% 10px;"
                 data-top-bottom="background-position: 50% -100px;"
                 data-bottom-top="background-position: 50% 100px;"
                 data-anchor-target="#slide-62"
            >
                <div class="hsContainer">
                    <a href="#slide-63" style="
        left: 0 !important;
            margin-left: 15% !important;
            margin-top: 20%;
            position: absolute;
            /* background-color: black; */
            left: 50%;
            height: 46px;
            margin-left: -23px;
            border-radius: 100%;
            box-sizing: border-box;"><span style="background-color: white !important;"></span>Scrollen</a>
                    <div class="hsContent"
                         data-center="opacity: 1"
                         data-center-top="opacity: 0"
                         data--100-bottom="opacity: 0;"
                         data-anchor-target="#slide-62"
                    >
                        <h2> <span style="color : red">2. Selbsthilfearbeit </span><p></p> Gründung und Betreuung von Selbsthilfegruppen wie  <span style="color : red">„Recovery groups“</span> vom Blue Cross, <span style="color : red">„Mother groups“ </span> , Gruppen für <span style="color : red">„reformed criminals“</span>  und <span style="color : red">„exstreetboys“</span>  sowie Sportgruppen gegen Sucht und Kriminalität.</h2>
                    </div>
                </div>
            </div>
        </section>

        <section id="slide-63" class="homeSlide">
            <div class="bcg"
                 data-center="background-position: 50% 0px;"
                 data-top-bottom="background-position: 50% -100px;"
                 data-bottom-top="background-position: 50% 100px;"
                 data-anchor-target="#slide-63"
            >
                <div class="hsContainer">
                    <a href="#slide-7" style="
        left: 0 !important;
            margin-left: 15% !important;
            margin-top: 20%;
            position: absolute;
            /* background-color: black; */
            left: 50%;
            height: 46px;
            margin-left: -23px;
            border-radius: 100%;
            box-sizing: border-box;"><span style="background-color: white !important;"></span>Scrollen</a>
                    <div class="hsContent"
                         data--50-bottom="opacity: 0;"
                         data--200-bottom="opacity: 1;"
                         data-center="opacity: 1"
                         data-200-top="opacity: 0"
                         data-anchor-target="#slide-63 h2"
                    >
                        <h2> <span style="color : red">3. Anlaufstellen bzw. Heime </span>  <p></p> Regionale Anlaufstellen, Ausstiegshilfen von der Straße und aus der Kriminalität, Kinderheime und Kinderpatenschaften, Aufbau von Reha-Einrichtungen. </h2>
                    </div>
                </div>



            </div>
        </section>

        <section id="slide-7" class="homeSlide">
            <div class="bcg"
                 data-center="background-position: 50% 10px;"
                 data-top-bottom="background-position: 50% -100px;"
                 data-bottom-top="background-position: 50% 100px;"
                 data-anchor-target="#slide-7"
            >
                <div class="hsContainer">
                    <a href="#slide-8" style="
        left: 0 !important;
            margin-left: 15% !important;
            margin-top: 20%;
            position: absolute;
            /* background-color: black; */
            left: 50%;
            height: 46px;
            margin-left: -23px;
            border-radius: 100%;
            box-sizing: border-box;"><span style="background-color: white !important;"></span>Scrollen</a>
                    <div class="hsContent"
                         data-center="opacity: 1"
                         data-center-top="opacity: 0"
                         data--100-bottom="opacity: 0;"
                         data-anchor-target="#slide-7"
                    >
                        <h2> <span style="color : red">Finanzierung und Organisationsteam in Deutschland</span> <p></p> Die   Finanzierung   der   Aktivitäten   wird   durch   Spenden   ermöglicht.   Der   Koordinator   des Projektes in Deutschland ist Dr. med. Klaus Richter. Er leitet einem festen Mitarbeiterkreis. Dieser   nimmt   Aufgaben   sowohl   in   Deutschland   als   auch   in   Ostafrika   wahr.   Durch   die ehrenamtliche Tätigkeit sind die Verwaltungskosten gering. Mitarbeiter sind ein- bis zweimal pro Jahr vor Ort <span style="color : red">(auf eigene Kosten) </span>. </h2>
                    </div>
                </div>
            </div>
        </section>


        <section id="slide-8" class="homeSlide">
            <div class="bcg"
                 data-center="background-position: 50% 0px;"
                 data-top-bottom="background-position: 50% -100px;"
                 data-bottom-top="background-position: 50% 100px;"
                 data-anchor-target="#slide-8"
            >
                <div class="hsContainer">
                    <div class="hsContent"
                         data-bottom-top="opacity: 0"
                         data-25p-top="opacity: 0"
                         data-top="opacity: 1"
                         data-anchor-target="#slide-8"
                    >
                        <h2> <span style="color : red">Träger</span> <p></p> Der Träger ist das in Elbingerode ansässige <span style="color : red">Diakonie-Krankenhaus „Harz“ </span>. Dieses kooperiert mit dem Diakonissenmutterhaus Elbingerode und dem deutschen Blauen Kreuz (Wuppertal). </h2>
                    </div>
                </div>
            </div>
        </section>

        <script>
            jQuery(document).ready(function( $ ) {
                $('.counter').counterUp({
                    delay: 50,
                    time: 5000
                });
            });
        </script>
        <script>
            var $j = jQuery.noConflict();
            $j(function() {
                $j('a[href*=\\#]:not([href=\\#])').on('click', function(e) {
                    e.preventDefault();
                    $j('html, body').animate({ scrollTop: $j($j(this).attr('href')).offset().top}, 500, 'linear');
                });
            });
        </script>

        <script>
            var $j = jQuery.noConflict();
            if(navigator.userAgent.match(/MSIE 10/i) || navigator.userAgent.match(/Trident\/7\./) || navigator.userAgent.match(/Edge\/12\./)) {
                $j('body').on("mousewheel", function () {
                    event.preventDefault();
                    var wd = event.wheelDelta;
                    var csp = window.pageYOffset;
                    window.scrollTo(0, csp - wd);
                });
            }
        </script>


        <script>

            jQuery(function ($) {

                var $window = jQuery(window);
                var scrollTime = 0.5;
                var scrollDistance = 150;


                $window.on("mousewheel DOMMouseScroll", function (event) {

                    event.preventDefault();

                    var delta = event.originalEvent.wheelDelta / 120 || -event.originalEvent.detail / 3;
                    var scrollTop = $window.scrollTop();
                    var finalScroll = scrollTop - parseInt(delta * scrollDistance);

                    TweenMax.to($window, scrollTime, {
                        scrollTo: {
                            y: finalScroll,
                            autoKill: true
                        },
                        ease: Power1.easeOut,
                        overwrite: 5
                    });

                });

            });
        </script>




        </div>
    </main>





<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='https://www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X','auto');ga('send','pageview');
</script>



<script src="https://cdn.smooch.io/smooch.min.js"></script>

<script>
    Smooch.init({ appToken: '06fbe0xhqw9tec9vnws3052ir'
    });
</script>
</body>
</html>




