<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
</head>

<body style="overflow-x: hidden">




<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<!-- Add your site or application content here -->

<main> <div id="wrapper">

        <section id="section03" class="demo" style="height: 120vh; padding-top: 10%">
            <div class="header-content-inner">
                <h1 id="homeHeading">„Du hast es gut,“ sagte mir ein Afrikaner.</h1>
                <h1 id="homeHeading2">„Wieso?“ fragte ich zurück?"</h1>

                <h1 id="p1">„Du kannst anderen helfen.“ Er lächelte. </h1>

                <h1 id="p2"> Können Sie auch? Steigen Sie zu!</h1>
                <a href="#content" style="
                color:white;

        position: absolute;
  font-size:30px;
        left: 50%;
        height: 46px;
        margin-left: -23px;
        border-radius: 100%;
        box-sizing: border-box;"><span></span>Scrollen</a>
            </div>
        </section>




        <div class="backg">


            <div class="row">
                <div class="col-md-4">

                    <div id="sidebar">

                        <div id="nav-anchor"></div>
                        <nav>
                            <ul>
                                <li><a href="#home">Teil des Teams werden</a></li>
                                <li><a href="#about">Kleines Geld hilft</a></li>
                                <li><a href="#services">Chancen für Kinder</a></li>
                                <li><a href="#blog">Helfen vor Ort</a></li>
                                <li><a href="#contact">Spendenbescheinigungen</a></li>

                            </ul>
                        </nav>
                    </div>

                </div>
                <div class="col-md-8">

                    <div id="content">



                        <section id="home" class="stylesections" style="padding-top: 5%; padding-right: 15%">
                            <h1>Wollen   Sie   im   Team   mitarbeiten? </h1>
                            <p>
                                Wir   machen   das   Projekt   bekannt, organisieren Basare, betreuen Stände, ermutigen zu Patenschaften, halten Info-Vorträge,   arbeiten  an   Website –   und   Facebook   –   Auftritten,   finden Gebetshilfe super, einige fahren jedes Jahr vor Ort (auf eigene Kosten) und anderes.
                            </p>

                        </section>


                        <section id="about" class="stylesections" style="padding-right: 15%; padding-top: 10%;">
                            <h1>Kleines Geld hilft und „ohne Moos nix los</h1>
                            <p>
                            <h2>Jeder Betrag hilft</h2> Unsere Verwaltung geschieht ehrenamtlich, so kommt viel Geld vor Ort an. „Moos“ wofür? Für Projekte kleiner oder großer Art, wie z.B. Geld für einen Fußball oder Hilfe für kranke Straßenkinder, als auch Unterstützung eines Seminars für Helfer oder Miethilfe für einen Treffpunkt im Slum oder… da ist viel möglich, wir geben Ihnen gerne Auskunft.
                            </p>


                        </section>


                        <section id="services" class="stylesections" style="padding-right: 15%; padding-top: 10%;">
                            <h1>Chancen für Kinder</h1>
                            <p>
                                in   Form   von   Patenschaften,insbesondere für Kinder in schweren Gefährdungssituationen. Wir suchenbesonders die, die wenige Freunde haben.  Auf spezielle Wünsche in Bezug auf Alter, Geschlecht usw., gehen wir nach Möglichkeit ein. Wir stellen Ihnen dann ein Kind vor. In größeren Abständen werden Sie über Ihr Kind informiert oder die Kinder schreiben selbst.  Mit welchem Beitrag müssten Sie monatlich rechnen? Das hängt von der Situation ab. Zum Beispiel für ein Slumkind 20 €, für ein älteres Straßenkind in Ausbildung 50 bis 75 € (für Schule, Wohnung, Essen, Kleidung usw.). Auch Teilpatenschaften oder Gruppenpatenschaften sind möglich.
                            <h2>Spenden zur freien Verfügung</h2> sind natürlich sehr willkommen. Bei der „Breite“ der Arbeit gibt es viele gute Möglichkeiten, sie zu verwenden.
                            </p>

                        </section>


                        <section id="blog" class="stylesections" style="padding-right: 15%; padding-top: 10%;">
                            <h1>Helfen vor Ort, wie läuft das?</h1>
                            <p>
                                Allen Respekt, dass Sie das erwägen. Unser Projekt stellt niemanden hier an, der dorthin entsendet wird. Gerne beraten wir aber über Möglichkeiten, vor Ort mitzuhelfen.
                            </p>
                            <h2>Möchten Sie mehr Informationen zu Einzelfragen? Dann nutzen Sie bitte diese Kontaktseite:</h2>

                            <form class="form contact"
                                  action="<?php echo $block->getFormAction(); ?>"
                                  id="contact-form"
                                  method="post"
                                 >
                                <fieldset class="fieldset">
                                    <legend class="legend"><span><?php  echo __('Write Us') ?></span></legend><br />
                                    <div class="field note no-label"><?php  echo __('Jot us a note and we’ll get back to you as quickly as possible.') ?></div>
                                    <div class="field name required">
                                        <label class="label" for="name"><span><?php  echo __('Name') ?></span></label>
                                        <div class="control">
                                            <input name="name" id="name" title="Your Name" class="input-text" type="text" data-validate="{required:true}"/>
                                        </div>
                                    </div>
                                    <div class="field email required">
                                        <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                                        <div class="control">
                                            <input name="email" id="email" title="Your Email" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                                        </div>
                                    </div>

                                    <div class="field comment required">
                                        <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?></span></label>
                                        <div class="control">
                                            <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                                        </div>
                                    </div>
                                </fieldset>
                                <div class="actions-toolbar">
                                    <div class="primary">
                                        <input type="hidden" name="hideit" id="hideit" value="" />
                                        <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                                            <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                                        </button>
                                    </div>
                                </div>
                            </form>


                        </section>


                        <section id="contact" class="stylesections" style="padding-right: 15%; padding-top: 10%;">
                            <h1>Spendenbescheinigungen </h1>
                            <p>
                                Diese werden am Anfang des neuen Jahres für das alteJahr ausgestellt. Wenn Sie zeitnah eine Bescheinigung wünschen, kontaktieren Sie uns einfach. Achtung! Wichtig ist, dass Sie auf der Überweisung Anschrift und Namen vermerken.
                            </p>


                        </section>



                    </div><!-- /#content -->

                </div>
            </div>
        </div>

        <script>
            var $j = jQuery.noConflict();
            $j(function() {
                $j('a[href*=\\#]:not([href=\\#])').on('click', function(e) {
                    e.preventDefault();
                    $j('html, body').animate({ scrollTop: $j($j(this).attr('href')).offset().top}, 500, 'linear');
                });
            });
        </script>


    </div> </main>




<script src="https://cdn.smooch.io/smooch.min.js"></script>

<script>
    Smooch.init({ appToken: '06fbe0xhqw9tec9vnws3052ir'

    });
</script>


<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='https://www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X','auto');ga('send','pageview');
</script>
</body>
</html>
