

<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
  






    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


</head>

<body style="overflow-x: hidden">


<header >
    <div class="header">

    </div>

</header>

<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<!-- Add your site or application content here -->

<main> <div id="wrapper">

        <div class="fullscreen-bg">
            <video autoplay loop muted class="fullscreen-bg__video"  id = "videomp4" style="margin-top: -10%" >
                <source src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/kenia.mp4'); ?>'" type='video/mp4; '>


            </video>
            <section class="content-section video-section" style="height: 60vh;" id="sec1">
                <div class="pattern-overlay" style="position:relative; height: 60vh;">

                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <h1>Kenia-Projekt</h1>
                                <h3>Projekt Hoffnung</h3>

                                <a href="#carouselContainer" style="    color: white !important;
                margin-top: 1%;
                position: absolute;
                /* background-color: black; */
                left: 50%;
                height: 46px;
                margin-left: -23px;
                border-radius: 100%;
                box-sizing: border-box;"><span style="background-color: transparent !important;"></span>Scrollen</a>
                            </div>
                        </div>
                    </div>

                </div>
            </section>



        </div>




        <div class="container" id="lala" >
            <div class="row">
                <h2 class="text-center" style="font-weight: 900; font-size:50px">
                    Die Grundpfeiler
                </h2>
                <h4 class="text-center" style="font-weight: 900">
                    Wir sind ein wachsendes Projekt, welches sich durch einzelne Grundpfeiler hervorhebt
                </h4>
                <div class="col-sm-6 col-md-3">
                    <div class="service">
                        <div class="header-holder">
                            <h3 style="font-weight:700">PERSONAL</h3>
                        </div>

                        <p class="description">
                            Wir sind ein Team aus wissensbegierigen, engagierten, sinnorientierten Menschen, solche wie Du oder Dein Nachbar.
                        </p>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="service">
                        <div class="header-holder">
                            <h3 style="font-weight:700">HILFE</h3>
                        </div>

                        <p class="description">
                            Wir helfen Straßenkindern und Suchtgefährdeten in Kenia, Uganda und Äthiopien. Wir sind mit Afrikanern dort befreundet, die ihren Leuten helfen. Besonderes Augenmerk liegt vor Ort auf Transparenz. Bei mangelnder Transparenz ziehen wir uns zurück.
                        </p>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="service">
                        <div class="header-holder">
                            <h3 style="color: #018fc9; font-weight:700">EHRENAMTLICH</h3>
                        </div>

                        <p class="description">
                            Wir arbeiten ehrenamtlich und reisen auch auf eigene Kosten nach Afrika, so kommt dein Geld auch zu fast 100% dort an.
                        </p>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="service">
                        <div class="header-holder">
                            <h3 style="color: #e84f40;font-weight:700"> MOTIVATION</h3>
                        </div>

                        <p class="description">
                            Wir teilen die Chancen, die wir von Gott und Mitmenschen erfahren haben mit dem Ziel, dass unserer Freunde ihre Ressourcen nutzen und entwickeln.
                        </p>
                    </div>
                </div>

            </div>
        </div>


        <div id="carouselContainer"style ="padding-top: 60px;">


            <div class="backgroundsection1">
                <div class="row" id="sec2" >

                    <div class="backgroundsectiontext">  Und so begann unsere kleine Geschichte</div>

                    <a href="#mitarbeiter11" style="  z-index:1000;  color: white !important;
            margin-top: 0.5%;
            position: absolute;
            /* background-color: black; */
            left: 50%;
            height: 46px;
            margin-left: -23px;
            border-radius: 100%;
            box-sizing: border-box;"><span style="background-color: transparent !important;"></span></a>
                </div>


            </div>


            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <!-- <ol class="carousel-indicators">
                   <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                   <li data-target="#myCarousel" data-slide-to="1"></li>
                   <li data-target="#myCarousel" data-slide-to="2"></li>
                   <li data-target="#myCarousel" data-slide-to="3"></li>
                   <li data-target="#myCarousel" data-slide-to="4"></li>
                 </ol>

                 <!-- Wrapper for slides -->

                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/slider1.jpg'); ?>' class = "mitarbeiter">
                        <div class="carousel-caption">
                            <h1>Wie alles begann</h1>
                            <p class="lead">Es lebte einmal vor langer, langer Zeit in einer kleinen Stadt im Harz ein Psychiater namens Klaus; der liebte Menschen. Klaus wollte weitergeben, was er selber erfahren hatte: Chancen und Ermutigung.</p>
                        </div>
                    </div>

                    <div class="item">
                        <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/slider2.jpg'); ?>' class = "mitarbeiter">
                        <div class="carousel-caption">
                            <h1>Ein Urlaub verändert das Leben von Menschen</h1>
                            <p class="lead">Vor 20 Jahren machte Klaus Urlaub in Kenia. Klaus sah die Not vor Ort. So dachte er sich: "Die Welt kannst du nicht retten, aber einzelnen Menschen helfen". Gesagt, getan!</p>
                        </div>
                    </div>

                    <div class="item">
                        <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/slider3.jpg'); ?>' class = "mitarbeiter">
                        <div class="carousel-caption">
                            <h1>Es entstehen Freundschaften</h1>
                            <p class="lead">Klaus fand in Kenia vor Ort Menschen, die bereit waren ihren eigenen Leuten zu helfen. Die Anzahl seiner Verbündeten stiegauf 100 Afrikaner allein in Kenia. Es konnte so Straßenkindern und Suchtgefährdeten geholfen werden.</p>
                        </div>
                    </div>

                    <div class="item">
                        <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/slider4.jpg'); ?>' class = "mitarbeiter">
                        <div class="carousel-caption">
                            <h1>Deutschland wird Teil des Projekts</h1>
                            <p class="lead">Aber auch in Deutschland war Klaus nicht alleine. Ihm schlossen sich viele Menschen an. Aus Klaus wurde das Kenia-Projekt.</p>
                        </div>
                    </div>

                    <div class="item">
                        <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/slider51.jpg'); ?>' class = "mitarbeiter">
                        <div class="carousel-caption">
                            <h1>Sei schlau! Sei wie Klaus!</h1>
                            <p class="lead">Das Kenia-Projekt sucht Dich! Einen tollen liebevollen Menschen, der sich gerne mit einbringt und ehrenamtlich hilft.</p>
                        </div>
                    </div>
                </div>

                <!-- Left and right controls -->
                <div class="left carousel-control" href="#myCarousel" role="button" data-slide="prev" style="color:black">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </div>
                <div class="right carousel-control" href="#myCarousel" role="button" data-slide="next" style="color:black">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </div>

            </div>
        </div>



        <div id="mitarbeiter11" style ="padding-top: 60px;">
            <div class="backgroundsection1"  >
                <div class="row" >

                    <div class="col-sm-4"><div class="backgroundsectiontext">Besteht seit <span class="counter" style="display: inline-block;">20</span> Jahren</div></div>
                    <div class="col-sm-4"><div class="backgroundsectiontext"><span class="counter" style="display: inline-block;">100</span> einheimische ehrenamtliche Mitarbeiter</div></div>
                    <div class="col-sm-4"><div class="backgroundsectiontext"> <span class="counter" style="display: inline-block;">100</span> Kinder</div></div>


                </div>


            </div>

            <section  style="width: 100%">
                <img src='<?php echo $this->getViewFileUrl('Kenia_Klaus::img/Mitarbeiter3.jpg'); ?>' class = "mitarbeiter">

            </section>

        </div>




        <script>
            $(function() {
                $('a[href*=\\#]:not([href=\\#])').on('click', function(e) {
                    e.preventDefault();
                    $('html, body').animate({ scrollTop: $($(this).attr('href')).offset().top}, 500, 'linear');
                });
            });
        </script>



        <script>
            jQuery(document).ready(function( $ ) {
                $('.counter').counterUp({
                    delay: 50,
                    time: 5000
                });
            });
        </script>

        <script>
            var $j = jQuery.noConflict();
            if(navigator.userAgent.match(/MSIE 10/i) || navigator.userAgent.match(/Trident\/7\./) || navigator.userAgent.match(/Edge\/12\./)) {
                $j('body').on("mousewheel", function () {
                    event.preventDefault();
                    var wd = event.wheelDelta;
                    var csp = window.pageYOffset;
                    window.scrollTo(0, csp - wd);
                });
            }
        </script>




    </div> </main>








<script>
    window.onload = function() {


        var offset1 =  $('#headerholder').height();
        var offset2 =  $('#pagetop').height();
        var offset3 = offset1- offset2 -20;

        $(".header").css({"margin-bottom": offset3});

        var offset4 = 10;
        $(".backgroundsection1").css({"margin-top": offset4});

    };


    window.onresize = function(event) {
        var offset1 =  $('#headerholder').height();
        var offset2 =  $('#pagetop').height();
        var offset3 = offset1- offset2 -20;

        $(".header").css({"margin-bottom": offset3});

        var offset4 = 10;
        $(".backgroundsection1").css({"margin-top": offset4});
    };


</script>
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='https://www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X','auto');ga('send','pageview');
</script>



<script src="https://cdn.smooch.io/smooch.min.js"></script>

<script>
    Smooch.init({ appToken: '06fbe0xhqw9tec9vnws3052ir'
    });
</script>
</body>
</html>
