<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">









</head>

<body style="overflow-x: hidden">


<header >
    <div class="header">

    </div>

</header>

<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<!-- Add your site or application content here -->

<main> <div id="wrapper">











        <script>
            var $j = jQuery.noConflict();
            $j(document).ready(function(){

                // Calling our plugin with a page id and an access token
                // that you will need to generate as explained in the tutorial:

                $j('#wall').facebookWall({

                    id:'275843585959972',
                    access_token:'EAAZArYZAr3ZCA0BAKSZCdqplSoE8iEo0A5ObW2mZAgyXh5LG1ngterKBcbGqXIbf8UrMV7977Sz0fufmy99eZA5L0DaebMByFis11AnWgwkfmWotardZCiur1DZCdZAT1UwmSoZAPw9xA573o34XujXl1xTKkvZAVpDsvAZD'
                });

            });
        </script>
        <div id="feedcontainer">

        </div>

        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-36251023-1']);
            _gaq.push(['_setDomainName', 'jqueryscript.net']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>

        <script>
            var $j = jQuery.noConflict();
            if(navigator.userAgent.match(/MSIE 10/i) || navigator.userAgent.match(/Trident\/7\./) || navigator.userAgent.match(/Edge\/12\./)) {
                $j('body').on("mousewheel", function () {
                    event.preventDefault();
                    var wd = event.wheelDelta;
                    var csp = window.pageYOffset;
                    window.scrollTo(0, csp - wd);
                });
            }
        </script>



    </div> </main>







<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='https://www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X','auto');ga('send','pageview');
</script>



<script src="https://cdn.smooch.io/smooch.min.js"></script>

<script>
    Smooch.init({ appToken: '06fbe0xhqw9tec9vnws3052ir'
    });
</script>
</body>
</html>




